title: GithubPages Blog
author: Aditya
email: aditya@xyz.com
description: > # this means to ignore newlines until "baseurl:"
  Studying Github Pages with Github's Course. It teaches everything from
  Customizing your Homepage, to adding blog post metadata

# social links
twitter_username: MeisterAdi # DO NOT include the @ character, or else the build will fail!
github_username:  Adi-075 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
